name: Update runtime_setting.yaml

on:
  repository_dispatch:
    types: [gpu-cluster-users-changed]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Parse payload
        env:
          PAYLOAD: ${{ github.event.client_payload }}
        run: |
          echo "Payload: ${PAYLOAD}"
