name: Update runtime_setting.yaml

on:
  repository_dispatch:
    types: [gpu-cluster-users-changed]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Payload
        env:
          PAYLOAD: ${{ github.event.client_payload.data }}
        run: |
          echo "Payload: ${PAYLOAD}"
