name: Update runtime_setting.yaml

on:
  repository_dispatch:
    types: [gpu-cluster-users-changed]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        env:
          PAYLOAD: ${{ github.event.client_payload }}
      - run: |
          echo "Payload: ${PAYLOAD}"
